// signin
export const AUTH = 'AUTH';
export const FETCH_SINGLEUSER = 'FETCH_SINGLEUSER';
export const LOGOUT = 'LOGOUT';
export const UPDATE_SINGLE_USER = 'UPDATE_SINGLE_USER';
export const IS_LOADING = 'IS_LOADING';
export const IS_NOT_LOADING = 'IS_NOT_LOADING';

// homePage
export const FETCH_HOMEPAGE = 'FETCH_HOMEPAGE';
export const CREATE_HOMEPAGE = 'CREATE_HOMEPAGE';
export const START_HOMEPAGE = 'START_HOMEPAGE';
export const END_HOMEPAGE = 'END_HOMEPAGE';
export const DELETE_HOMEPAGE = 'DELETE_HOMEPAGE';
export const UPDATE_HOMEPAGE = 'UPDATE_HOMEPAGE';

// foodPage
export const FETCH_FOODPAGE = 'FETCH_FOODPAGE';
export const FETCH_FOOD_BY_SEARCH = 'FETCH_FOOD_BY_SEARCH';
export const CREATE_FOODPAGE = 'CREATE_FOODPAGE';
export const START_FOODPAGE = 'START_FOODPAGE';
export const END_FOODPAGE = 'END_FOODPAGE';
export const DELETE_FOODPAGE = "DELETE_FOODPAGE";
export const UPDATE_FOODPAGE = "UPDATE_FOODPAGE";

// payment
export const FETCH_PAYMENT_FOOD = 'FETCH_PAYMENT_FOOD';
export const FETCH_PAYMENT_CLIENT_FOOD = 'FETCH_PAYMENT_CLIENT_FOOD';
export const FETCH_PAYMENT_DELETE = 'FETCH_PAYMENT_DELETE';